FROM node:20-alpine AS builder

WORKDIR /app

COPY package*.json ./
COPY tsconfig*.json ./

RUN npm ci

COPY /src ./src

RUN npm run build --workspace=server

FROM node:20-alpine

RUN npm ci

COPY --from=builder /app/dist ./dist

COPY .env.example .env.example

ENV NODE_ENV=production

EXPOSE 3000

CMD ["node", "dist/index.js"]
