version: "1.0"

project:
  name: mcp-meilisearch
  description: MCP server that provides a bridge between AI models and Meilisearch.
  version: 1.0.0

startCommand:
  type: stdio
  configSchema:
    type: object
    properties:
      MEILISEARCH_HOST:
        type: string
        default: http://localhost:7700
        description: URL for the Meilisearch instance
      MEILISEARCH_API_KEY:
        type: string
        default: ""
        description: API key for Meilisearch, if required
      MEILISEARCH_TIMEOUT:
        type: number
        default: 5000
        description: Timeout for Meilisearch API requests in milliseconds.
      PORT:
        type: number
        default: 3000
        description: Port for the MCP server to listen on.
    required:
      - MEILISEARCH_HOST
      - MEILISEARCH_API_KEY
      - PORT
  commandFunction: |-
    (config) => ({
      command: 'node',
      args: ['dist/index.js'], // Assumes 'dist' contains the built server
      env: {
        NODE_ENV: 'production',
        MEILISEARCH_HOST: config.MEILISEARCH_HOST,
        MEILISEARCH_API_KEY: config.MEILISEARCH_API_KEY,
        MEILISEARCH_TIMEOUT: config.MEILISEARCH_TIMEOUT.toString(),
        PORT: config.PORT.toString() // Pass port to the application
      }
    })
  exampleConfig:
    MEILISEARCH_HOST: http://localhost:7700
    MEILISEARCH_API_KEY: "your-meilisearch-api-key"
    MEILISEARCH_TIMEOUT: 5000
    PORT: 3000

workspace:
  packages:
    - path: server
      type: app
      target: node

dependencies:
  production:
    "@modelcontextprotocol/sdk": "^1.10.1"
    express: "^5.1.0"
    axios: "^1.9.0"
    zod: "^3.24.4"
  development:
    typescript: "^5.8.3"
    "@types/express": "^5.0.1"
    "@types/node": "^22.14.0"

build:
  commands:
    clean:
      description: Clean build artifacts and distribution folder.
      command: |
        rm -rf server/build
        rm -rf dist

    install-deps:
      description: Install root and workspace dependencies.
      command: npm install

    build-app:
      description: Build the server application.
      command: npm run build --workspace=server

    package-app:
      description: Create a distribution package for the server.
      command: |
        echo "Packaging application into dist/ directory..."
        mkdir -p dist
        cp -r server/build/* dist/
        echo '{
          "name": "mcp-meilisearch-server-dist",
          "version": "1.0.0",
          "main": "index.js",
          "type": "module",
          "dependencies": {
            "@modelcontextprotocol/sdk": "^1.10.1",
            "express": "^5.1.0",
            "axios": "^1.9.0",
            "zod": "^3.24.4"
          }
        }' > dist/package.json
        echo "Application packaged successfully."

pipelines:
  default:
    - build-app

  build-package:
    - clean
    - build-app
    - package-app

  ci:
    - clean
    - install-deps
    - build-app
    - package-app
